baseURL = 'https://anantnrg.github.io'
languageCode = 'en-us'
title = 'Anant Narayan'
theme = "PaperMod"
enableRobotsTXT = true
enableEmoji = true
# pygmentsUseClasses = true
# pygmentsCodefences = true

[params]
ShowBreadCrumbs = false
disableThemeToggle = false
ShowCodeCopyButtons = false
env = "production"
keywords = [
    "Blog",
    "Rust",
    "Linux",
    "Embedded Systems",
    "Microcontrollers",
    "FPGA",
    "Haskell",
    "Lua",
    "Python",
    "Config",
    "Wayland",
    "GNU",
    "C",
    "C++",
    "CPP",
    "Cpp",
    "C/C++",
    "Artix",
    "Arch",
    "Runit",
    "GitHub",
    "How",
    "How-to",
    "Install",
    "Learn",
    "Programming",
    "Coding",
    "JavaScript",
    "Hugo",
    "Go",
    "Static",
    "Site",
    "SSG",
]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params.homeInfoParams]
Title = "Hey, \U0001F44B"
Content = "I'm Anant Narayan, a 14 year old Robotics Developer, Rust programmer and a Linux nerd. I love programming FPGAs and writing code in low level systems languages like Rust, C/C++ and Go. I (currently) use Artix Linux (with Runit), BSPWM, NeoVim and Neovide (NeoVim GUI). I occasionally use VS Code for WebDev. I also love hacking in Linux and trying to rewrite everything in Rust lol. I'm currently working on [Strata](https://github.com/stratawm/strata), a Wayland compositor writen in Rust and configured in Lua!"

[[params.socialIcons]]
name = "github"
url = "https://github.com/anantnrg"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/anantnrg"

[[params.socialIcons]]
name = "reddit"
url = "https://reddit.com/u/anantnrg"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/fVdux2fc"

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@anantnrg"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "About"
url = "/about"
weight = 30

[[menu.main]]
name = "GitHub"
url = "https://github.com/anantnrg"
weight = 40

[[menu.main]]
name = "Strata"
url = "https://github.com/stratawm/strata"
weight = 50
